[package]
name = "scyllax-macros"
description = "Macros for scyllax"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
anyhow = { workspace = true }
darling = { version = "0.20", features = ["suggestions"] }
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "derive", "extra-traits"] }
