[package]
name = "example"
description = "an example using scyllax"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = false

[dependencies]
anyhow = { workspace = true }
scylla = { workspace = true }
scyllax = { path = "../" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
pretty_assertions = "1"
