[package]
name = "scyllax-example"
edition = "2021"
version = "0.1.0"
publish = false

[dependencies]
anyhow = { workspace = true }
scylla = { workspace = true }
scyllax = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
