repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-toml
          - id: check-yaml
          - id: pretty-format-json
            args: ["--indent=4", "--autofix"]
          - id: check-added-large-files

    # - repo: https://github.com/doublify/pre-commit-rust
    #   rev: v1.0
    #   hooks:
    #       - id: fmt
    #       - id: cargo-check
    #       - id: clippy

    - repo: local
      hooks:
        - id: format
          name: format
          entry: bash -c 'cargo make format'
          language: system
          types: [rust]
          pass_filenames: false
        - id: lint
          name: lint
          entry: bash -c 'cargo make lint'
          language: system
          types: [rust]
          pass_filenames: false
