[workspace]
members = ["example", "scyllax", "scyllax-macros"]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/trufflehq/scyllax"
keywords = ["scylla", "cassandra", "orm", "sqlx", "trufflehq", "truffle", "youtube", "twitch"]
authors = [
    "Carter Himmel <carter@truffle.vip>"
]
homepage = "https://github.com/trufflehq/scyllax#readme"

[workspace.dependencies]
scyllax-macros = { verison = "0.1.0-alpha", path = "scyllax-macros" }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json", "tracing-log", "parking_lot"] }
tokio = { version = "1", features = ["full", "tracing"] }
scylla = { version = "0.9" }
serde_json = { version = "1", features = ["preserve_order"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["serde", "v1", "std", "fast-rng"] }
darling = "0.20"
trybuild = "1"

[profile.release]
debug = 1

[profile.dev.package.backtrace]
opt-level = 3
