version: "3.8"

services:
  scylla:
    image: scylladb/scylla:latest
    volumes:
      - scylla_storage:/var/lib/scylla
    command:
      - --smp 1
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
      - "9180:9180"

volumes:
  scylla_storage:
