[package]
name = "scyllax-cli"
description = "The CLI for scyllax -- mainly managing migrations"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = "../README.md"

[[bin]]
name = "scyllax"
path = "src/bin/scyllax.rs"

[dependencies]
tokio = { workspace = true }
clap = { version = "4", features = ["derive", "env"] }
clap_complete = { version = "4" }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
anyhow = "1.0.52"
url = { version = "2.2.2", default-features = false }
async-trait = "0.1"
console = "0.15.0"
promptly = "0.3.0"
scylla = { workspace = true }
scyllax = { path = "../" }
serde_json = "1.0.73"
serde = { version = "1.0.132", features = ["derive"] }
glob = "0.3.0"
tracing = { workspace = true }
filetime = "0.2.22"
time = { version = "0.3.28", features = ["formatting"] }
sha2 = "0.10.7"
