[package]
name = "scyllax"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1"
getrandom = "0.2"
mac_address = "1"
once_cell = "1"
scylla = { workspace = true }
scyllax-macros = { workspace = true }
thiserror = "1"
tracing = { workspace = true }
uuid = { workspace = true }
