[book]
src = "src"
title = "scyllax Documentation"
authors = ["Carter Himmel <carter@truffle.vip>"]
language = "en"

[output.html]
git-repository-url = "https://github.com/trufflehq/scyllax/tree/main/book"
edit-url-template  = "https://github.com/trufflehq/scyllax/edit/main/book/{path}"

[output.html.playground]
runnable = false

[output.html.redirect]
"/example.html" = "../example/README.md"
