name: Deploy Book

on:
  push:
    branches: [main]
    paths:
      - 'book/**'
      - '.github/workflows/book.yml'

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Website
    runs-on: scyllax-runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install mdbook
        uses: taiki-e/install-action@mdbook

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Run Clippy
        working-directory: book
        run: mdbook build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: book/book

  deploy:
    name: Deploy Website
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: scyllax-runner
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
